### PR TITLE
Added content from Wiki with Markdown compilation and styling

### PR DESCRIPTION
**Pull request by curran**
Here's a start at migration from the Wiki to the Web site. See `docs/compileMarkdown.js`, which compiles the markdown files and makes them look kind of like Wiki pages.

Main files are [compileMarkdown.js](https://github.com/curran/d3.github.com/blob/master/docs/compileMarkdown.js) and [htmlTemplate.hbs](https://github.com/curran/d3.github.com/blob/master/docs/htmlTemplate.hbs).

Here's what one of the pages looks like:
wikitoweb

### CODE REVIEW

**Comment by mbostock** [comment]
Thanks for starting this. It seems that GitHub Pages support Markdown compilation via [Jekyll](https://help.github.com/articles/using-jekyll-with-pages/), so I was wondering if you think it would be possible to check-in the Markdown files as-is, and have a `_config.yml` file that sets up Jekyll for the Markdown pages, without interfering with the hand-coded HTML pages?

**Comment by curran** [comment]
That should be possible, in which case the docs from the wiki could live in the gh-pages branch of the d3.github.com repo, which would isolate them from the hand-coded HTML. I have no experience with Jekyll, but I can try to get this working and send a pull request on the gh-pages branch.

**Comment by mbostock** [comment]
Since this is a specially-named repo, the master branch serves as the gh-pages branch in a not-otherwise-specially-named repo. So the Markdown files would live alongside the HTML files, but I believe Jekyll won’t touch the HTML files, so it should be okay.

**Comment by curran** [comment]
Ah yes, I see.

I moved the Markdown files to live alongside the HTML files, serving the old Wiki Markdown pages via Jekyll. When I run `bundle exec jekyll serve` locally, I can see both `http://localhost:4000/Partition-Layout.html` (generated page) and `http://localhost:4000/index.html` (hand-coded page), so you are right that they can live happily together with Jekyll.

The main files for this migration are

* [_layouts/page.html](https://github.com/curran/d3.github.com/blob/master/_layouts/page.html) This is the HTML template using Jekyll conventions.
* [migrate.js](https://github.com/curran/d3.github.com/blob/master/migrate.js) This is a one-time migration script that adds the "frontmatter" required by Jekyll to each Markdown source file.

There are some funky things happening where Jekyll is rendering the Markdown differently than the Wiki, so more tweaking needs to be done, but this is a start.

**Comment by curran** [comment]
Actually, here's another idea altogether - what about migrating *only* the example gallery page to use Jekyll? The other pages suffer from Markdown dialect discrepancies between GitHub and Jekyll such that each page will need to be modified in order to look good with Jekyll. I feel like the example gallery is the page that the community wants to edit the most. The other pages will be relatively static documentation pages, and could be migrated later one by one if necessary.

**Comment by mbostock** [comment]
I’m not sure what to do, yet.

I’ve asked GitHub to provide email notifications for wiki changes so that I can monitor it for spam edits and deletions. Currently there is no way to be notified (short of writing your own server or polling), so spam edits often go undetected for days. I’ve also asked Slack to implement wiki change event notifications for its GitHub integration; currently they ignore wiki events. If either entity implements support for wiki change notification it will be sufficient for me to monitor and unlock the wiki, so we can likely go back to how it was before (at least until spammers become much more aggressive).

The immediacy of editing the wiki is a huge draw. In past projects where I’ve had documentation in a GitHub repo that requires a pull request, almost no one bothered to submit a pull request. But many more people don’t seem to mind clicking the Edit button, making a change, and clicking Save. I think the fact that it’s immediate and doesn’t require approval makes the wiki much more inclusive, even if it presents the risk of spam or erroneous edits. The immediacy is especially important to the gallery.

I think the documentation is probably fairly stable at this point, so I wouldn’t mind it being in a repo rather than a wiki. But the gallery would probably benefit from a dedicated server (running on Heroku, say) that accepts nominations for the gallery and maybe allows upvoting. I don’t have time right now to implement such a server, but I might have to if there’s no progress on the wiki notification front.

**Comment by curran** [comment]
Oh yeah I totally see what you mean with the immediacy of editing.

If this helps at all - `git log` on the Wiki repo seems to work for detecting changes - I can see

```
commit 7d3df5920b2186d53a87729cfe542cd3959cd249
Author: Mike Bostock <mbostock@gmail.com>
Date:   Sun Mar 15 15:01:01 2015 -0700

    Remove spam.

commit 8516f1f2601088fe094183b8dfec596e0304d175
Author: ihsanashabi12 <ikhsan_ashabi@gmail.com>
Date:   Mon Mar 16 05:00:48 2015 +0700

    service solahart kelapa gading

commit 4699a613b5dbe1e3c0e9b2032b2c62af30beefa7
Author: Neil Atkinson <neil@new-bamboo.co.uk>
Date:   Sun Mar 15 12:00:56 2015 +0000

    Add bi-directional hierarchical sankey.

commit 691d73eebbbc1e19baaa1755ad513ecfc3eb15cb
Author: donosaputra <donosaputra953@yahoo.co.id>
Date:   Sun Mar 15 17:51:35 2015 +0700

    SERVICE SOLAHART AL
```

Pseudocode for email notifications might look like:

```
every 10 minutes,
  git log > oldLog
  git pull
  git lot > newLog
  if (oldLog != newLog)
    email new log
```

This should be straightforward to implement with Node, Child Process API and the [mail command](http://stackoverflow.com/questions/20318770/send-mail-from-linux-terminal-in-one-line). Here's some Node code that does this:

```
var exec = require('child_process').execSync;
var tenMinutes = 1000 * 60 * 10;
setInterval(function(){
  var oldLog = exec('git log -n 5').toString();
  exec('git pull');
  var newLog = exec('git log -n 5').toString();
  if(oldLog !== newLog){
    exec('git log -n 5 > log.txt');
    exec('cat log.txt | mail -s "D3 Wiki Update ' + new Date() + '" user@gmail.com');
    console.log('sent mail');
  }
}, tenMinutes);
```

**Comment by mbostock** [comment]
The API references are moving to the README files of each D3 module for D3 4.0. I’d like to replace the  gallery with a website that makes it easier for people to submit, screenshot, and upvote entries… but I have no immediate plans to implement that.

**Pull request closed without merging**
